# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -v
      - name: Generate coverage report
        run: |
          coverage report -m
      - name: Check coverage threshold
        run: |
          coverage report --fail-under=90
      - name: Generate HTML coverage report (optional)
        if: always()
        run: |
          coverage html
      - name: Upload coverage report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/